### ISSUE TITLE
Wheels no longer seem to work on Google Colab

### ISSUE THREAD

**Issue by jslegers** [metrolobo/xformers_wheels#2]
AFAIK your precompiled wheels worked fine on Google Colab until today.

Now I'm getting an error that it's not supported by the platform. They probably did a version upgrade of something.

**Comment by jslegers** [comment]
See also https://github.com/ShivamShrirao/diffusers/issues/152

**Comment by metrolobo** [comment]
I see. Added new ones for 3.8 now though seems fixed by OP already anyway. 👍
