### ISSUE TITLE
xformers-0.0.14.dev0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by 3venjd** [metrolobo/xformers_wheels#3]
what happened with that version when i tried to install is broken
![error](https://user-images.githubusercontent.com/31141661/206800383-50388fef-514c-4261-afc2-31a680fbeb2b.png)

**Comment by metrolobo** [comment]
Colab updated to python 3.8, new one here https://github.com/metrolobo/xformers_wheels/releases/download/4c06c79_various6/xformers-0.0.15.dev0_4c06c79.d20221201-cp38-cp38-linux_x86_64.whl
